USE ROLE {{ env }}_DATA_SCHEMACHANGE_ROLE;
CREATE OR REPLACE DATABASE {{ env }}_VENDORS;
USE DATABASE {{ env }}_VENDORS;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS REFINED;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION;