USE ROLE {{ env }}_DATA_SCHEMACHANGE_ROLE;
CREATE OR REPLACE DATABASE {{ env }}_VENDORS;
USE DATABASE {{ env }}_VENDORS;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA REFINED;
CREATE OR REPLACE SCHEMA CONSUMPTION;