USE ROLE {{ env }}_DATA_SCHEMACHANGE_ROLE;
CREATE DATABASE IF NOT EXISTS {{ env }}_PEOPLESOFT;
USE DATABASE {{ env }}_PEOPLESOFT;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS REFINED;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION;