USE ROLE {{ env }}_DATA_SCHEMACHANGE_ROLE;
CREATE OR REPLACE DATABASE {{ env }}_PEOPLESOFT;
USE DATABASE {{ env }}_PEOPLESOFT;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA REFINED;
CREATE OR REPLACE SCHEMA CONSUMPTION;