CREATE OR REPLACE USER {{ env }}_INFER_SCHEMACHANGE_USER
MUST_CHANGE_PASSWORD = TRUE
DEFAULT_ROLE = {{ env }}_SCHEMACHANGE_ROLE
PASSWORD = 'ABC'
COMMENT = 'This is a dummy user for SDI schemachange tasks';