--INFRA_db.SCHEMACHANGE.CHANGE_HISTORY
CREATE USER IF NOT EXISTS {{ env }}_SCHEMACHANGE_USER
MUST_CHANGE_PASSWORD = TRUE
DEFAULT_ROLE = {{ env }}_SCHEMACHANGE_ROLE
DEFAULT_WAREHOUSE = {{ env }}_SCHEMACHANGE_WH;