name: snowflake-devops-infra-projects

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy to (DEV, UAT, PROD)'
        required: true
        default: DEV
        type: choice
        options:
          - DEV
          - UAT
          - PROD

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    # Use the repository-level ENV variable here (no need for workflow_dispatch input)
    environment: ${{ vars.ENV }}  # Reference the repository-level ENV variable

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Use Python 3.8.x
      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      # Set environment variable
      - name: Set environment variable
        env:
          ENV: ${{ vars.ENV }}  # Use the repository-level ENV variable directly
          SF_USERNAME: ${{ vars.SF_USERNAME }}  # Pull SF_USERNAME from your environment-specific variables
        run: |
          echo "Setting environment variables..."
          echo "ENV=${{ vars.ENV }}" >> $GITHUB_ENV  # Set ENV from the repository-level variable
          echo "SF_USERNAME=${{ vars.SF_USERNAME }}" >> $GITHUB_ENV

      # Run schemachange
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}
          SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
          SNOWFLAKE_USER: ${{ vars.SF_USERNAME }}
          SF_ROLE: ${{ vars.SF_ROLE }}
          SF_DATABASE: ${{ vars.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          ENV: ${{ vars.ENV }}  # Use the repository-level ENV variable
        run: |
          echo "Deploying to environment: ${ENV}"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/100_infra_objs/001_roles -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE --vars '{"env": "'${ENV}'", "main_user": "'${SF_USERNAME}'"}' -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
