name: snowflake-devops-infra-projects

# Controls when the action will run. 
on:
  push:
    branches:
      - main   # Single branch for all environments
    paths:
      - '100_infra_objs/001_roles/**'
      #- '100_infra_objs/004_data_objs/**'
      

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    # Specify that the job will run for the selected environment based on the ENV repository secret
    environment: ${{ vars.ENV }} # ENV is  now defined at the repository level

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Set environment variable
        env:
          ENV: ${{ vars.ENV }}  
          SF_USERNAME: ${{ vars.SF_USERNAME }}  # Pull SF_USERNAME from your environment-specific variables
        run: | 
          echo "Setting environment variables..."
          echo "ENV=${{ vars.ENV }}" >> $GITHUB_ENV
          echo "SF_USERNAME=${{ vars.SF_USERNAME }}" >> $GITHUB_ENV

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}  # Use environment-specific variables for SF_ACCOUNT
          SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}  # Use environment-specific variables for SF_WAREHOUSE
          SNOWFLAKE_USER: ${{ vars.SF_USERNAME }}  # Use environment-specific variables for SF_USERNAME
          SF_ROLE: ${{ vars.SF_ROLE }}  # Use environment-specific variables for SF_ROLE
          SF_DATABASE: ${{ vars.SF_DATABASE }}  # Use environment-specific variables for SF_DATABASE
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}  # Use environment-specific secrets for SF_PASSWORD
          ENV: ${{ vars.ENV }}  # Make ENV available in the run script
        run: |
          echo "Deploying to environment: ${ENV}"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/100_infra_objs/001_roles -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE --vars '{"env": "'${ENV}'", "main_user": "'${SF_USERNAME}'"}' -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
